security:
    # Password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator  # <-- Add this line
            logout:
                path: app_logout
                target: /login
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_redirect_by_role  # La route de redirection après connexion
                enable_csrf: true

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Access Control
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

# Configurations for the "test" environment
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10  # <-- Fixed comment here
