parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    api_ninjas_email_api_key: '%env(API_NINJAS_EMAIL_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Service\HistoriqueLogger:
        class: App\Service\HistoriqueLogger
        arguments:
            $logFile: '%kernel.project_dir%/var/log/historique.log'

    App\Service\ProfanityFilter:
        class: App\Service\ProfanityFilter
        arguments:
            $apiKey: '%env(API_NINJAS_API_KEY)%'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    App\Service\PasswordGeneratorService:
        class: App\Service\PasswordGeneratorService
        arguments:
            $apiKey: '%env(API_NINJAS_API_KEY)%'
